# -*- coding: utf-8 -*-
"""LAB4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4az7FwvsuAeACFRDQC6VewqE4Q7UnJB
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

#RELU
st.set_page_config(page_title="Sigmoid Activation Function", layout="centered")

st.title("Sigmoid Activation Function")
st.write(
    """
    **Sigmoid function** maps values into the range (0, 1):
    \\[
    f(x) = \\frac{1}{1 + e^{-x}}
    \\]
    """
)

# Sidebar
st.sidebar.header("Settings")
x_min = st.sidebar.slider("Minimum x value", -10.0, 0.0, -6.0)
x_max = st.sidebar.slider("Maximum x value", 0.0, 10.0, 6.0)
num_points = st.sidebar.slider("Number of points", 100, 2000, 500)

# Generate data
x = np.linspace(x_min, x_max, num_points)
x_tensor = torch.from_numpy(x).float()

sigmoid = nn.Sigmoid()
y = sigmoid(x_tensor).numpy()

# Plot
fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlabel("x")
ax.set_ylabel("Sigmoid(x)")
ax.set_title("Sigmoid Activation Function")
ax.axvline(0)

st.pyplot(fig)

#TANH
st.set_page_config(page_title="Tanh Activation Function", layout="centered")

st.title("Tanh Activation Function")
st.write(
    """
    **Hyperbolic Tangent (Tanh)** maps values into the range (-1, 1):
    \\[
    f(x) = \\tanh(x)
    \\]
    """
)

# Sidebar
st.sidebar.header("Settings")
x_min = st.sidebar.slider("Minimum x value", -10.0, 0.0, -5.0)
x_max = st.sidebar.slider("Maximum x value", 0.0, 10.0, 5.0)
num_points = st.sidebar.slider("Number of points", 100, 2000, 500)

# Generate data
x = np.linspace(x_min, x_max, num_points)
x_tensor = torch.from_numpy(x).float()

tanh = nn.Tanh()
y = tanh(x_tensor).numpy()

# Plot
fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlabel("x")
ax.set_ylabel("tanh(x)")
ax.set_title("Tanh Activation Function")
ax.axhline(0)
ax.axvline(0)

st.pyplot(fig)

#SIGMOID
st.set_page_config(page_title="Sigmoid Activation Function", layout="centered")

st.title("Sigmoid Activation Function")
st.write(
    """
    **Sigmoid function** maps values into the range (0, 1):
    \\[
    f(x) = \\frac{1}{1 + e^{-x}}
    \\]
    """
)

# Sidebar
st.sidebar.header("Settings")
x_min = st.sidebar.slider("Minimum x value", -10.0, 0.0, -6.0)
x_max = st.sidebar.slider("Maximum x value", 0.0, 10.0, 6.0)
num_points = st.sidebar.slider("Number of points", 100, 2000, 500)

# Generate data
x = np.linspace(x_min, x_max, num_points)
x_tensor = torch.from_numpy(x).float()

sigmoid = nn.Sigmoid()
y = sigmoid(x_tensor).numpy()

# Plot
fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlabel("x")
ax.set_ylabel("Sigmoid(x)")
ax.set_title("Sigmoid Activation Function")
ax.axvline(0)

st.pyplot(fig)